CREATE SEQUENCE member_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000;

CREATE TABLE "MEMBER"(
	NUM NUMBER NOT NULL,
	NAME VARCHAR2(20),
	BIRTHDAY DATE,
	CONSTRAINT MEMBER_PK PRIMARY KEY(NUM)
);

INSERT INTO HR."MEMBER"
(NUM, NAME, BIRTHDAY)
VALUES(MEMBER_SEQ.NEXTVAL, '김휘준', TO_DATE('1111-11-1','YYYY-MM-DD'));

INSERT INTO HR."MEMBER"
(NUM, NAME, BIRTHDAY)
VALUES(MEMBER_SEQ.NEXTVAL, '김휘준', TO_DATE('1111-12-1','YYYY-MM-DD'));


