SELECT * FROM BOARD;

CREATE SEQUENCE BOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;

CREATE TABLE BOARD(
	BOARD_NUM NUMBER(10),
	BOARD_TITLE VARCHAR2(50),
	BOARD_CONTENTS VARCHAR2(3000),
	MEMBER_ID VARCHAR2(50),
	BOARD_DATE DATE,
	CONSTRAINT BOARD_PK PRIMARY KEY(BOARD_NUM),
	CONSTRAINT BOARD_FK FOREIGN KEY (MEMBER_ID) REFERENCES "MEMBER"(MEMBER_ID)
);

ALTER TABLE board add(board_readcount NUMBER(10));
SELECT * FROM BOARD;

CREATE TABLE FILES(
	file_name varchar2(100),
	board_num,
	CONSTRAINT files_pk PRIMARY key(file_name),
	CONSTRAINT files_fk FOREIGN KEY(board_num) REFERENCES board(board_num)
);

SELECT * FROM files;
SELECT * FROM "MEMBER";
INSERT INTO BOARD values(BOARD_SEQ.NEXTVAL, '아무글','안녕하세요','joon',sysdate,0);
INSERT INTO BOARD values(BOARD_SEQ.NEXTVAL, '아무글','안녕하세요','joon1',sysdate,0);

SELECT Board_seq.currval FROM DUAL;